=== VoidMystery/xml_parser/apartment.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.task.org/apartment"
        xmlns:ap="http://www.task.org/apartment"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified">

    <element name="apartments">
        <complexType>
            <sequence>
                <element name="apartment" maxOccurs="400">
                    <complexType>
                        <sequence>
                            <element name="floor" type="ap:floorType"/>
                            <element name="room" type="ap:roomNumberType"/>
                            <element name="balcony" type="ap:balconyType"/>
                        </sequence>
                        <attribute name="id" type="positiveInteger" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
        <unique name="UniqueID">
            <selector xpath="ap:apartment"/>
            <field xpath="@id"/>
        </unique>
        <unique name="UniqueRoom">
            <selector xpath="ap:apartment"/>
            <field xpath="ap:room"/>
        </unique>
    </element>

    <simpleType name="floorType">
        <restriction base="positiveInteger">
            <minInclusive value="1"/>
            <maxInclusive value="20"/>
        </restriction>
    </simpleType>
    <simpleType name="roomNumberType">
        <restriction base="string">
            <pattern
                    value="([2][0][0-1][0-9])|([2][0][2][0])|([1][0-9][0-1][0-9])|([1][0-9][2][0])|([1-9][0-1][0-9])|([1-9][2][0])"/>
        </restriction>
    </simpleType>
    <simpleType name="balconyType">
        <restriction base="string">
            <pattern
                    value="true|false"/>
        </restriction>
    </simpleType>
</schema>

=== VoidMystery/xml_parser/apartment.xml
<?xml version="1.0" encoding="UTF-8" ?>
<apartments
        xmlns="http://www.task.org/apartment"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.task.org/apartment apartment.xsd" >
    <apartment id="1">
        <floor>1</floor>
        <room>101</room>
        <balcony>true</balcony>
    </apartment>
    <apartment id="2">
        <floor>1</floor>
        <room>102</room>
        <balcony>false</balcony>
    </apartment>
</apartments>

=== VoidMystery/xml_parser/apartment2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ap:apartments
        xmlns:ap="http://www.task.org/apartment"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.task.org/apartment apartment.xsd" >
    <ap:apartment id="1">
        <ap:floor>1</ap:floor>
        <ap:room>101</ap:room>
        <ap:balcony>true</ap:balcony>
    </ap:apartment>
    <ap:apartment id="2">
        <ap:floor>1</ap:floor>
        <ap:room>102</ap:room>
        <ap:balcony>false</ap:balcony>
    </ap:apartment>
</ap:apartments>
